# Generated by Django 4.2 on 2023-04-27 01:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("image", models.CharField(max_length=200)),
                (
                    "content",
                    models.TextField(
                        verbose_name=django.core.validators.MinLengthValidator(30)
                    ),
                ),
                ("importance", models.PositiveSmallIntegerField()),
                ("github", models.URLField()),
                ("explanation", models.TextField()),
            ],
        ),
    ]
